services:
  - type: web
    name: nobetci-api
    runtime: docker
    region: frankfurt
    plan: free
    healthCheckPath: /schedule/health
    envVars:
      - key: PORT
        value: 8080
      - key: DEBUG
        value: "false"
